[package]
name = "user-service-rpc"
version = "0.1.0"
edition = "2021"


[dependencies]
tonic = { workspace = true}
prost = { workspace = true}
prost-types = { workspace = true}


[build-dependencies]
tonic-build = "0.12.1"