version: '3.8'

services:
  user-service-server:
    hostname: User-Service-Server
    container_name: User-Service-Server
    build:
      context: ../
      dockerfile: deployment/Dockerfile-build
      target: User-Service-Server
    depends_on:
      - user-service-database
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    stdin_open: true
    tty: true
    networks:
      - user-service-network

  user-service-test-client:
    hostname: User-Service-Test-Client
    container_name: User-Service-Test-Client
    build:
      context: ../
      dockerfile: deployment/Dockerfile-build
      target: User-Service-Test-Client
    depends_on:
      - user-service-server
    stdin_open: true
    tty: true
    networks:
      - user-service-network

  user-service-database:
    hostname: User-Service-db
    image: postgres:latest
    container_name: User-Service-Db
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-service-network

volumes:
  postgres_data:

networks:
  user-service-network: