version: '3.8'

services:
  dev:
    image: rust:latest
    container_name: user-service
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/database
    depends_on:
      - db
    networks:
      - dev_network

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge

volumes:
  postgres_data:
